### ISSUE TITLE
Local corporation NIF doesn't validate

### ISSUE THREAD

**Issue by jvmonjo** [singuerinc/better-dni#106]
Local government NIF does not validate.

For example
```
isValid('P4622000J'); // should be true, but is false

```

**Comment by jvmonjo** [comment]
Sorry. I've just realized your library is not meant to validate CIFs, which is what my example is, a town hall CIF. So it follows the CIF validation rules.

On the other hand it would be cool to support CIFs too.

**Comment by singuerinc** [comment]
ok, so it's a new feature: Validate CIF.
I'll create a new ticket with the feature request and close this one:
https://github.com/singuerinc/better-dni/issues/108
