### ISSUE TITLE
NPM module includes arrow functions

### ISSUE THREAD

**Issue by lexanth** [singuerinc/better-dni#47]
The NPM module you're publishing includes arrow functions (and maybe other ES6 features?).

We want to use this library, but need to support IE11 which doesn't support arrow functions (https://caniuse.com/#feat=arrow-functions).

This is the only library we're using which publishes a non-ES5-compatible NPM module. Any chance you could either switch to standard function declarations or produce a babel-transpiled JS bundle?
Alternatively, at least a note on the README that IE11 is not supported would be useful.

Workaround:
Include this library in our webpack config so that babel-loader picks it up.

**Comment by singuerinc** [comment]
Hi @lexanth, no problem, I can easily change the arrows to regular functions. Will do it ASAP.

**Comment by singuerinc** [comment]
@lexanth 

I have created a branch that includes a version that is compiled with Babel, I did a quick test in IE11 and it works.

Could you please check in your environment?

PR:
https://github.com/singuerinc/better-dni/pull/48

bundle IE11 ready:
https://github.com/singuerinc/better-dni/blob/feature/refactor-arrow-functions/dist/index.js

**Comment by lexanth** [comment]
Awesome, works great (I was in the middle of asking if you were going to replace the arrows or just use babel when I saw the PR!).

**Comment by singuerinc** [comment]
Great, I will merge it later.

**Comment by lexanth** [comment]
@singuerinc Thanks for the quick fix!
